### PR TITLE
Todo example with gorm

### PR DESCRIPTION
**Pull request by bastianwegge**
As discussed in #1 here's a small example and really just a first shot for a gorm.io integration. I've not worked with go-chi before but just ported some stuff I already had done with gofiber before.

Would love to hear your thoughts about this @Howard3

### CODE REVIEW

**Comment by Howard3** [comment]
Hey there! That was really fast! Thank you, first glance everything looks good, I'll need to make a modification to how the database is selected so that we can swap dynamically a file versus turso, this can be done by an environment variable.

I haven't gone super in depth yet as today's fathers day in Brasil and I have a 9 month old but I'll check the rest out tonight.

How was your experience working in this design / toolset?

**Comment by Howard3** [comment]
Great work! This is an awesome first contribution, thank you! I will need to modify it to be dynamic on SQLite definition, but this is fantastic.

**Comment by Howard3** [comment]
I may  need to add a limit to the todo and some code to reset it on some interval as well, since we'll host it on https://chia-goths.fly.dev/

**Comment by bastianwegge** [comment]
Feedback on the developer experience:
- We could add something like [air](https://github.com/cosmtrek/air) to avoid having to restart on code-changes
- The automatic reload of the templates is very nice
- Picking something on top of tailwindcss (like [daisyUI](https://daisyui.com/)) makes things easier to design
- What convinced me was the separation of code/templates each in a separate folder

So all in all it's a very solid experience. I have to get used to Go still.
Thanks for accepting my contribution.

**Comment by Howard3** [comment]
- air, will add this. Agreed it helps a lot. I had a problem in another project where it wasn't closing the original process always, but I think that it might have been an older version.
- daisyUI: I've never heard of this before, looks interesting - thanks for introducing it to me! I think it could be a good option for an app to demonstrate how a single app may use it. This is a good example of where the tailwind config in each app may be useful, since it'll be loaded in as a plugin in that app

I appreciate the feedback as it'll help me improve this for more users going forward

**Comment by Howard3** [comment]
Added air:
https://github.com/Howard3/chia-goths/commit/5f4da8254b9e8a219392c06cc23bf82eb2a74764

I'll work later this week on getting everything to main

**Pull request merged**
